server:
  port: 30010

spring:
  application:
    name: silincemall-cart
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080 #配置Sentinel dashboard地址
        port: 8719 # 默认8719端口，加入被占用会从8719开始依次+1扫描，直至找到为被占用饿的端口
  redis:
    host: 47.97.191.*** # 上线了需要使用别的redis，不能和缓存混合着用
feign:
  sentinel:
    enabled: true
# 线程池配置
silincemall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10

management:
  endpoints:
    web:
      exposure:
        include: '*'