management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  cloud:
    # alibaba oss 对象存储配置
    alicloud:
      access-key: 
      secret-key: 
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
      sendsms:
        phone: 18106524119
    nacos:
      server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080 #配置Sentinel dashboard地址
        port: 8719 # 默认8719端口，加入被占用会从8719开始依次+1扫描，直至找到为被占用饿的端口
  application:
    name: silincemall-third-party
feign:
  sentinel:
    enabled: true
server:
  port: 30000
