spring:
  datasource:
    username: ***
    password: ***
    url: jdbc:mysql://47.97.191.***:3306/silincemall_wms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080 #配置Sentinel dashboard地址
        port: 8719 # 默认8719端口，加入被占用会从8719开始依次+1扫描，直至找到为被占用饿的端口
    alibaba:
      seata:
        tx-service-group: silincemall-ware-fescar-service-group
  application:
    name: silincemall-ware
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  rabbitmq:
    host: 127.0.0.1
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual # 手动ack

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml  # classpath*:则表示不止扫描自己的类路径，包括我应用的其他依赖的类路径
  global-config:
    db-config:
      id-type: auto # 配置主键自增

server:
  port: 11000
feign:
  sentinel:
    enabled: true
logging:
  level:
    cn.silince: debug
management:
  endpoints:
    web:
      exposure:
        include: '*'